using System.IO;
using System.Security.Cryptography;
using Microsoft.Win32;

namespace S8Cam;

public sealed record VirtualCameraDriverStatus(bool Ready, string DeviceName, string? DllPath, string Message);

/// <summary>Per-user DirectShow registration of the OBS camera module, for both consumer architectures.</summary>
public static class VirtualCameraDriver {
    internal const string CameraClsid = "{A3FCE0F5-3493-419F-958A-ABA1250EC20B}";
    internal const string CameraCategory = "{860BB310-5D01-11d0-BD3B-00A0C911CE86}";
    private static readonly object installLock = new();

    // IFilterMapper2's NV12 capture-pin registration, generated by OBS 32.2.2 DllRegisterServer.
    private static readonly byte[] filterData = Convert.FromHexString(
        "0200000000002000010000000000000030706933080000000000000001000000" +
        "0000000000000000307479330000000038000000480000007669647300001000" +
        "800000AA00389B714E56313200001000800000AA00389B71");

    public static VirtualCameraDriverStatus GetStatus() {
        try {
            using var classes64 = RegistryKey.OpenBaseKey(RegistryHive.ClassesRoot, RegistryView.Registry64);
            var camera64 = ReadRegistration(classes64, x64: true);
            if (!camera64.Ready) return camera64;
            using var classes32 = RegistryKey.OpenBaseKey(RegistryHive.ClassesRoot, RegistryView.Registry32);
            var camera32 = ReadRegistration(classes32, x64: false);
            if (!camera32.Ready) return camera64 with {
                Ready = false, Message = "32-битная камера требует установки/восстановления; 64-битная зарегистрирована"
            };
            return camera64.DeviceName == camera32.DeviceName ? camera64 : camera64 with {
                Message = $"Камера зарегистрирована: {camera64.DeviceName} (64-бит) / {camera32.DeviceName} (32-бит)"
            };
        } catch (Exception ex) {
            return new(false, "H3H Cam", null, "Не удалось проверить регистрацию камеры: " + ex.Message);
        }
    }

    internal static VirtualCameraDriverStatus ReadRegistration(RegistryKey classes, bool x64) {
        using var server = classes.OpenSubKey($@"CLSID\{CameraClsid}\InprocServer32");
        using var device = classes.OpenSubKey($@"CLSID\{CameraCategory}\Instance\{CameraClsid}");
        var name = device?.GetValue("FriendlyName") as string ?? "H3H Cam";
        var dll = server?.GetValue(null) as string;
        if (string.IsNullOrWhiteSpace(dll)) return new(false, name, dll, "Виртуальная камера не установлена");
        dll = Environment.ExpandEnvironmentVariables(dll.Trim('"'));
        if (!IsDriverBinary(dll, x64)) return new(false, name, dll, "Модуль камеры отсутствует или повреждён — требуется восстановление");
        using var camera = classes.OpenSubKey($@"CLSID\{CameraClsid}");
        if ((camera?.GetValue(null) as string)?.StartsWith("H3H Cam", StringComparison.Ordinal) == true) {
            var folderHash = Path.GetFileName(Path.GetDirectoryName(dll))?.Split('-')[0];
            if (folderHash?.Length == 16 && folderHash.All(Uri.IsHexDigit)) {
                try {
                    using var input = File.OpenRead(dll);
                    if (!Convert.ToHexString(SHA256.HashData(input)).StartsWith(folderHash, StringComparison.OrdinalIgnoreCase))
                        return new(false, name, dll, "Сохранённый модуль камеры повреждён — требуется восстановление");
                } catch {
                    return new(false, name, dll, "Не удалось прочитать модуль камеры — требуется восстановление");
                }
            }
        }
        if (device?.GetValue("CLSID") is not string clsid || !clsid.Equals(CameraClsid, StringComparison.OrdinalIgnoreCase))
            return new(false, name, dll, "Камера не зарегистрирована в списке устройств — требуется восстановление");
        if (device.GetValue("FilterData") is not byte[] data || data.Length == 0)
            return new(false, name, dll, "Отсутствует описание видеовыхода — требуется восстановление");
        return new(true, name, dll, $"Камера зарегистрирована: {name}");
    }

    internal static bool IsDriverBinary(string path, bool x64) {
        try {
            using var reader = new BinaryReader(File.Open(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete));
            if (reader.ReadUInt16() != 0x5A4D) return false;
            reader.BaseStream.Position = 0x3C;
            int peOffset = reader.ReadInt32();
            if (peOffset < 64 || peOffset > reader.BaseStream.Length - 6) return false;
            reader.BaseStream.Position = peOffset;
            return reader.ReadUInt32() == 0x4550 && reader.ReadUInt16() == (x64 ? 0x8664 : 0x14C);
        } catch { return false; }
    }

    public static string? FindDriverDll(bool x64 = true) {
        var filename = x64 ? "obs-virtualcam-module64.dll" : "obs-virtualcam-module32.dll";
        var candidates = new[] {
            Path.Combine(AppContext.BaseDirectory, "tools", "virtualcam", filename),
            Path.Combine(AppContext.BaseDirectory, filename),
            Path.Combine(Environment.CurrentDirectory, "tools", "virtualcam", filename),
            Path.Combine(Environment.CurrentDirectory, "windows", "native", "virtualcam", filename),
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "obs-studio", "data", "obs-plugins", "win-dshow", filename)
        };
        return candidates.FirstOrDefault(path => IsDriverBinary(path, x64));
    }

    // Keep the COM server outside the unpacked ZIP. Moving/deleting a portable folder
    // must not leave camera registrations pointing at a missing DLL.
    internal static string InstallInto(RegistryKey userClasses, string sourceDll, string installDir, bool x64) {
        if (!IsDriverBinary(sourceDll, x64)) throw new IOException("Модуль виртуальной камеры отсутствует или повреждён. Распакуйте Windows ZIP целиком.");
        string hash;
        using (var input = File.OpenRead(sourceDll)) hash = Convert.ToHexString(SHA256.HashData(input)).ToLowerInvariant();
        var targetDir = Path.Combine(installDir, hash[..16]);
        Directory.CreateDirectory(targetDir);
        var target = Path.Combine(targetDir, Path.GetFileName(sourceDll));
        // Content-addressed paths also avoid replacing DLLs loaded by a video-call app.
        if (File.Exists(target)) {
            using var input = File.OpenRead(target);
            if (Convert.ToHexString(SHA256.HashData(input)).ToLowerInvariant() != hash) {
                // Do not replace a DLL that another application may already have loaded.
                targetDir = Path.Combine(installDir, hash[..16] + "-" + Guid.NewGuid().ToString("N"));
                Directory.CreateDirectory(targetDir);
                target = Path.Combine(targetDir, Path.GetFileName(sourceDll));
            }
        }
        if (!File.Exists(target)) File.Copy(sourceDll, target);
        using (var camera = userClasses.CreateSubKey($@"CLSID\{CameraClsid}")) {
            camera.SetValue(null, "H3H Cam (Virtual Camera)");
            using var server = camera.CreateSubKey("InprocServer32");
            server.SetValue(null, Path.GetFullPath(target));
            server.SetValue("ThreadingModel", "Both");
        }
        using (var device = userClasses.CreateSubKey($@"CLSID\{CameraCategory}\Instance\{CameraClsid}")) {
            device.SetValue("CLSID", CameraClsid);
            device.SetValue("FriendlyName", "H3H Cam");
            device.SetValue("FilterData", filterData, RegistryValueKind.Binary);
        }
        return target;
    }

    public static bool EnsureInstalled() {
        lock (installLock) {
            var installDir = Path.GetFullPath(Path.Combine(Settings.DataDir, "virtualcam"));
            foreach (bool x64 in new[] { true, false }) {
                var view = x64 ? RegistryView.Registry64 : RegistryView.Registry32;
                using var mergedClasses = RegistryKey.OpenBaseKey(RegistryHive.ClassesRoot, view);
                var status = ReadRegistration(mergedClasses, x64);
                using var user = RegistryKey.OpenBaseKey(RegistryHive.CurrentUser, view);
                using var classes = user.CreateSubKey(@"Software\Classes");
                using var owned = classes.OpenSubKey($@"CLSID\{CameraClsid}");
                bool ownedByH3H = (owned?.GetValue(null) as string)?.StartsWith("H3H Cam", StringComparison.Ordinal) == true;
                bool stable = status.DllPath?.StartsWith(installDir + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase) == true;
                // Reuse an existing OBS installation; migrate only our own old portable registration.
                if (status.Ready && (!ownedByH3H || stable)) continue;
                var source = FindDriverDll(x64);
                if (source == null) {
                    throw new FileNotFoundException($"Не найден {(x64 ? "64" : "32")}-битный модуль виртуальной камеры. Распакуйте Windows ZIP целиком, включая tools/virtualcam.");
                }
                InstallInto(classes, source, installDir, x64);
                if (!ReadRegistration(mergedClasses, x64).Ready) throw new IOException("Не удалось проверить регистрацию виртуальной камеры");
            }
            return GetStatus().Ready;
        }
    }

    public static Task<bool> InstallAsync() => Task.Run(EnsureInstalled);

    public static bool UninstallUserLevel() {
        lock (installLock) {
            foreach (var view in new[] { RegistryView.Registry64, RegistryView.Registry32 }) {
                using var user = RegistryKey.OpenBaseKey(RegistryHive.CurrentUser, view);
                using var classes = user.OpenSubKey(@"Software\Classes", writable: true);
                using var camera = classes?.OpenSubKey($@"CLSID\{CameraClsid}");
                if ((camera?.GetValue(null) as string)?.StartsWith("H3H Cam", StringComparison.Ordinal) != true) continue;
                camera?.Dispose();
                classes!.DeleteSubKeyTree($@"CLSID\{CameraClsid}", throwOnMissingSubKey: false);
                classes.DeleteSubKeyTree($@"CLSID\{CameraCategory}\Instance\{CameraClsid}", throwOnMissingSubKey: false);
            }
            return true;
        }
    }
}
